name: Build & Push GIMS Images

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-frontend
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-backend
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gims-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
