import express from 'express';
import verifyJWT from '../middlewares/verifyJWT';
import { getAllFuelIssueRecords, getFuelIssueRecordById, createFuelIssueRecord, updateFuelIssueRecord, deleteFuelIssueRecord, getFuelTypes, getNacCodes } from '../controllers/fuelIssueRecordsController';
const router = express.Router();
router.get('/', verifyJWT, getAllFuelIssueRecords);
router.get('/:id', verifyJWT, getFuelIssueRecordById);
router.post('/', verifyJWT, createFuelIssueRecord);
router.put('/:id', verifyJWT, updateFuelIssueRecord);
router.delete('/:id', verifyJWT, deleteFuelIssueRecord);
router.get('/filters/fuel-types', verifyJWT, getFuelTypes);
router.get('/filters/nac-codes', verifyJWT, getNacCodes);
export default router;
