import express from 'express';
import { getDailyIssueReport, exportDailyIssueReport, generateStockCardReport, previewStockCard, getDailyReceiveSummary, getDailyRequestSummary, getDailyRRPSummary, getDailyRequestDetails, getDailyReceiveDetails, getDailyRRPDetails, getDashboardTotals, getReceiveRRPReport, exportReceiveRRPReport, getCurrentStockReport, exportCurrentStockReport, getStockHistory, exportStockHistory, getRRPDetailsForNAC, getIssueDetailsForNAC, getReceiveDetailsForNAC, fixRemainingBalances, fixIssueCostsAndBalances } from '../controllers/reportController';
import { generateRequestReceiveReport, exportRequestReceiveReport, generateTenderReceiveReport, generateBorrowHistoryReport } from '../controllers/reportController';
import verifyJWT from '../middlewares/verifyJWT';
import { checkPermissions } from '../middlewares/auth';
const router = express.Router();
router.get('/dailyissue', verifyJWT, getDailyIssueReport);
router.post('/dailyissue/export', verifyJWT, exportDailyIssueReport);
router.post('/stockcard', verifyJWT, generateStockCardReport);
router.post('/stockcard/preview', verifyJWT, previewStockCard);
router.get('/current-stock', verifyJWT, getCurrentStockReport);
router.post('/current-stock/export', verifyJWT, exportCurrentStockReport);
router.get('/request-receive', verifyJWT, generateRequestReceiveReport);
router.post('/request-receive/export', verifyJWT, exportRequestReceiveReport);
router.get('/tender-receive', verifyJWT, generateTenderReceiveReport);
router.get('/borrow-history', verifyJWT, generateBorrowHistoryReport);
router.get('/daily/receive', verifyJWT, getDailyReceiveSummary);
router.get('/daily/request', verifyJWT, getDailyRequestSummary);
router.get('/daily/rrp', verifyJWT, getDailyRRPSummary);
router.get('/dashboard/totals', verifyJWT, getDashboardTotals);
router.get('/daily/request/details', verifyJWT, getDailyRequestDetails);
router.get('/daily/receive/details', verifyJWT, getDailyReceiveDetails);
router.get('/daily/rrp/details', verifyJWT, getDailyRRPDetails);
router.get('/receive-rrp', verifyJWT, getReceiveRRPReport);
router.post('/receive-rrp/export', verifyJWT, exportReceiveRRPReport);
router.get('/stock-history', verifyJWT, checkPermissions(['can_see_stock_history']), getStockHistory);
router.post('/stock-history/export', verifyJWT, checkPermissions(['can_see_stock_history']), exportStockHistory);
router.get('/rrp-details', verifyJWT, checkPermissions(['can_see_stock_history']), getRRPDetailsForNAC);
router.get('/issue-details', verifyJWT, checkPermissions(['can_see_stock_history']), getIssueDetailsForNAC);
router.get('/receive-details', verifyJWT, checkPermissions(['can_see_stock_history']), getReceiveDetailsForNAC);
router.post('/fix-remaining-balances', verifyJWT, fixRemainingBalances);
router.post('/fix-issue-costs', verifyJWT, fixIssueCostsAndBalances);
export default router;
