import express from 'express';
import { createRequest, getPendingRequests, getRequestItems, updateRequest, approveRequest, rejectRequest, forceCloseRequest, forceCloseRequestItem, getRequestById, searchRequests, getLastRequestInfo, uploadReferenceDocument, checkDuplicateRequest, getNextRequestNumber, deleteReferenceDocument, markRequestAsSkippable, resolveRequestTarget, getRequestEquipmentOptionsHandler } from '../controllers/requestController';
import verifyJWT from '../middlewares/verifyJWT';
import { printRequest } from '../controllers/printController';
const router = express.Router();
router.get('/resolve-target', verifyJWT, resolveRequestTarget);
router.get('/equipment-options', getRequestEquipmentOptionsHandler);
router.get('/pending', verifyJWT, getPendingRequests);
router.get('/search', verifyJWT, searchRequests);
router.get('/items/:requestNumber', verifyJWT, getRequestItems);
router.get('/getlastrequestinfo', verifyJWT, getLastRequestInfo);
router.get('/next-request-number', verifyJWT, getNextRequestNumber);
router.get('/duplicate', verifyJWT, checkDuplicateRequest);
router.post('/create', verifyJWT, createRequest);
router.put('/:requestNumber', verifyJWT, updateRequest);
router.put('/:requestNumber/approve', verifyJWT, approveRequest);
router.put('/:requestNumber/reject', verifyJWT, rejectRequest);
router.put('/items/:id/force-close', verifyJWT, forceCloseRequestItem);
router.put('/:requestNumber/force-close', verifyJWT, forceCloseRequest);
router.get('/:id', verifyJWT, getRequestById);
router.get('/:requestNumber/print', printRequest);
router.post('/upload-ref-doc', verifyJWT, uploadReferenceDocument);
router.put('/:requestNumber/mark-skippable', verifyJWT, markRequestAsSkippable);
router.delete('/:requestNumber/reference-doc', verifyJWT, deleteReferenceDocument);
export default router;
