import express from 'express';
import { getRRPConfig, getRRPItems, createRRP, getPendingRRPs, approveRRP, rejectRRP, updateRRP, getRRPById, searchRRP, getLatestRRPDetails, verifyRRPNumber, uploadRRPReferenceDoc, deleteRRPReferenceDoc } from '../controllers/rrpController';
import { printRRP } from '../controllers/printController';
const router = express.Router();
router.get('/config', getRRPConfig);
router.get('/items', getRRPItems);
router.get('/items/:id', getRRPById);
router.get('/pending', getPendingRRPs);
router.get('/search', searchRRP);
router.get('/getlatestrrpdetails/:type', getLatestRRPDetails);
router.get('/verifyRRPNumber/:rrpNumber', verifyRRPNumber);
router.post('/create', createRRP);
router.post('/approve/:rrpNumber', approveRRP);
router.post('/reject/:rrpNumber', rejectRRP);
router.put('/update/:rrpNumber', updateRRP);
router.post('/upload-ref-doc', uploadRRPReferenceDoc);
router.delete('/:rrpNumber/reference-doc', deleteRRPReferenceDoc);
router.get('/:rrpNumber/print', printRRP);
export default router;
