import express from 'express';
import { getFiscalYear, updateFiscalYear, getRequestAuthorityDetails, updateRequestAuthorityDetails, getRRPAuthorityDetails, updateRRPAuthorityDetails, getRRPSuppliers, addRRPSupplier, updateRRPSupplier, deleteRRPSupplier, getFuelSettings, updateFuelSettings, getInspectionUsers, addInspectionUser, updateInspectionUser, deleteInspectionUser, getRequestingAuthorityList, getRequestEmailConfig, updateRequestEmailConfig, toggleMailSending, verifySMTP } from '../controllers/settingsController';
import verifyJWT from '../middlewares/verifyJWT';
const router = express.Router();
router.use(verifyJWT);
router.get('/fiscal-year', getFiscalYear);
router.put('/fiscal-year', updateFiscalYear);
router.get('/request/authority-details', getRequestAuthorityDetails);
router.put('/request/authority-details', updateRequestAuthorityDetails);
router.get('/rrp/authority-details', getRRPAuthorityDetails);
router.put('/rrp/authority-details', updateRRPAuthorityDetails);
router.get('/rrp/suppliers', getRRPSuppliers);
router.post('/rrp/suppliers', addRRPSupplier);
router.put('/rrp/suppliers/:id', updateRRPSupplier);
router.delete('/rrp/suppliers/:id', deleteRRPSupplier);
router.get('/rrp/inspection-users', getInspectionUsers);
router.post('/rrp/inspection-users', addInspectionUser);
router.put('/rrp/inspection-users/:id', updateInspectionUser);
router.delete('/rrp/inspection-users/:id', deleteInspectionUser);
router.get('/fuel', getFuelSettings);
router.put('/fuel', updateFuelSettings);
router.get('/request/email-config', getRequestEmailConfig);
router.put('/request/email-config', updateRequestEmailConfig);
router.post('/request/email-toggle', toggleMailSending);
router.get('/request/email-smtp-test', verifySMTP);
router.get('/request/requesting-authorities', getRequestingAuthorityList);
export default router;
