export const queryKeys = {
  search: {
    all: ['search'] as const,
    stock: (params: Record<string, unknown>) => ['search', 'stock', params] as const,
    item: (id: number) => ['search', 'item', id] as const,
  },
  request: {
    all: ['request'] as const,
    pending: () => ['request', 'pending'] as const,
    items: (requestNumber: string) => ['request', 'items', requestNumber] as const,
    details: (requestNumber: string) => ['request', 'details', requestNumber] as const,
    search: (params: Record<string, unknown>) => ['request', 'search', params] as const,
    duplicate: (params: Record<string, unknown>) => ['request', 'duplicate', params] as const,
    nextNumber: () => ['request', 'next-number'] as const,
    lastInfo: () => ['request', 'last-info'] as const,
    print: (requestNumber: string) => ['request', 'print', requestNumber] as const,
  },
  receive: {
    all: ['receive'] as const,
    pending: () => ['receive', 'pending'] as const,
    details: (id: number) => ['receive', 'details', id] as const,
    records: (params: Record<string, unknown>) => ['receive', 'records', params] as const,
    recordsFilters: () => ['receive', 'records', 'filters'] as const,
    previousImage: (nacCode: string) => ['receive', 'previous-image', nacCode] as const,
    unitConversion: (params: Record<string, unknown>) => ['receive', 'unit-conversion', params] as const,
  },
  rrp: {
    all: ['rrp'] as const,
    search: (params: Record<string, unknown>) => ['rrp', 'search', params] as const,
    pending: () => ['rrp', 'pending'] as const,
    config: () => ['rrp', 'config'] as const,
    print: (rrpNumber: string) => ['rrp', 'print', rrpNumber] as const,
  },
  issue: {
    all: ['issue'] as const,
    pending: () => ['issue', 'pending'] as const,
    pendingFuel: () => ['issue', 'pending-fuel'] as const,
  },
  dashboard: {
    all: ['dashboard'] as const,
    totals: (params: Record<string, unknown>) => ['dashboard', 'totals', params] as const,
    dailyIssue: (params: Record<string, unknown>) => ['dashboard', 'daily-issue', params] as const,
    dailyRequest: (params: Record<string, unknown>) => ['dashboard', 'daily-request', params] as const,
    dailyReceive: (params: Record<string, unknown>) => ['dashboard', 'daily-receive', params] as const,
    dailyRrp: (params: Record<string, unknown>) => ['dashboard', 'daily-rrp', params] as const,
  },
  settings: {
    all: ['settings'] as const,
    requestingAuthorities: () => ['settings', 'requesting-authorities'] as const,
    rrp: {
      authorityDetails: () => ['settings', 'rrp', 'authority-details'] as const,
      suppliers: (params: Record<string, unknown>) => ['settings', 'rrp', 'suppliers', params] as const,
      inspectionUsers: () => ['settings', 'rrp', 'inspection-users'] as const,
    },
    request: {
      authorityDetails: () => ['settings', 'request', 'authority-details'] as const,
    },
    nacUnits: (params: Record<string, unknown>) => ['settings', 'nac-units', params] as const,
    nacUnitsByNac: (nacCode: string) => ['settings', 'nac-units', 'nac', nacCode] as const,
    nacUnitsSearch: (params: Record<string, unknown>) => ['settings', 'nac-units', 'search', params] as const,
  },
  assets: {
    all: ['assets'] as const,
    types: () => ['assets', 'types'] as const,
    type: (id: number) => ['assets', 'types', id] as const,
    list: (params: Record<string, unknown>) => ['assets', 'list', params] as const,
    detail: (id: number) => ['assets', 'detail', id] as const,
  },
  reports: {
    all: ['reports'] as const,
    requestReceive: (params: Record<string, unknown>) => ['reports', 'request-receive', params] as const,
    receiveRrp: (params: Record<string, unknown>) => ['reports', 'receive-rrp', params] as const,
    currentStock: (params: Record<string, unknown>) => ['reports', 'current-stock', params] as const,
    stockHistory: (params: Record<string, unknown>) => ['reports', 'stock-history', params] as const,
    rrpDetails: (params: Record<string, unknown>) => ['reports', 'rrp-details', params] as const,
    issueDetails: (params: Record<string, unknown>) => ['reports', 'issue-details', params] as const,
    receiveDetails: (params: Record<string, unknown>) => ['reports', 'receive-details', params] as const,
    fuel: {
      dieselWeeklyCheck: (params: Record<string, unknown>) => ['reports', 'fuel', 'diesel-weekly-check', params] as const,
      dieselWeekly: (params: Record<string, unknown>) => ['reports', 'fuel', 'diesel-weekly', params] as const,
      dieselWeeklySummary: (params: Record<string, unknown>) => ['reports', 'fuel', 'diesel-weekly-summary', params] as const,
    },
  },
  records: {
    all: ['records'] as const,
    request: (params: Record<string, unknown>) => ['records', 'request', params] as const,
    requestFilters: () => ['records', 'request', 'filters'] as const,
    receive: (params: Record<string, unknown>) => ['records', 'receive', params] as const,
    receiveFilters: () => ['records', 'receive', 'filters'] as const,
  },
  locationPhrases: {
    active: () => ['location-phrases', 'active'] as const,
  },
  borrowSources: {
    active: () => ['borrow-sources', 'active'] as const,
    all: () => ['borrow-sources'] as const,
  },
  permissions: {
    all: () => ['permissions'] as const,
    user: (userId: number) => ['permissions', 'user', userId] as const,
  },
};
